// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLe7OO7LrVu_HRVT2s32FbOGu_CNammhU',
    appId: '1:155082002517:web:b10331a87f60e81c3f04dc',
    messagingSenderId: '155082002517',
    projectId: 'subitogusto',
    authDomain: 'subitogusto.firebaseapp.com',
    storageBucket: 'subitogusto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHwa_Ld-Wck1YUyojOI2sVuOlFqh9CIUM',
    appId: '1:155082002517:android:850a99043e2caf063f04dc',
    messagingSenderId: '155082002517',
    projectId: 'subitogusto',
    storageBucket: 'subitogusto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutuYImlBq1MGsnkORwItif46Z391CkQk',
    appId: '1:155082002517:ios:bb57c3efff5494fd3f04dc',
    messagingSenderId: '155082002517',
    projectId: 'subitogusto',
    storageBucket: 'subitogusto.firebasestorage.app',
    iosBundleId: 'com.subitogusto.subitoGusto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAutuYImlBq1MGsnkORwItif46Z391CkQk',
    appId: '1:155082002517:ios:bb57c3efff5494fd3f04dc',
    messagingSenderId: '155082002517',
    projectId: 'subitogusto',
    storageBucket: 'subitogusto.firebasestorage.app',
    iosBundleId: 'com.subitogusto.subitoGusto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLe7OO7LrVu_HRVT2s32FbOGu_CNammhU',
    appId: '1:155082002517:web:cf87b9506c92c8f53f04dc',
    messagingSenderId: '155082002517',
    projectId: 'subitogusto',
    authDomain: 'subitogusto.firebaseapp.com',
    storageBucket: 'subitogusto.firebasestorage.app',
  );
}
